[package]
name = "spi"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[profile.release]
opt-level = 'z'  # Optimize for size.

[dependencies]
consts = { path="../../../lib/consts"}
model = { path = "../../model" }
clock = { path = "../../clock" }
tock-registers = "0.7.0"
