[package]
name = "qemu-armv7"
version = "0.1.0"
authors = ["Ronald G. Minnich <rminnich@gmail.com>"]
edition = "2018"

[dependencies]
console = { path = "../../../console" }
driver = { path = "../../../drivers/driver"}
uart = { path = "../../../drivers/uart"}
cpu = { path = "../../../cpu/armltd/cortex-a9"}
payload = { path = "../../../../payloads/payload"}
zimage = { path = "../../../../payloads/external/zimage"}

[profile.release]
opt-level = 'z'  # Optimize for size.
