[package]
name = "qemu-armv7"
version = "0.1.0"
authors = ["Ronald G. Minnich <rminnich@gmail.com>"]
edition = "2018"

[dependencies]
console = { path = "../../../console" }
cpu = { path = "../../../cpu/armltd/cortex-a9"}
payloads = { path = "../../../../payloads"}
device_tree = { path = "../../../lib/device_tree" }

[dependencies.drivers]
path = "../../../drivers"
features = ["pl011"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
