# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "starfive-visionfive1-main"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-nb = "1.0.0"
nb = "1"
riscv = { version = "0.10.1", features = [] }
rustsbi = "0.3.2"
spin = "0.9"

log = { path = "../../../../lib/log" }

# TODO
# [dependencies.oreboot-soc]
# path = "../../../../soc"
# features = ["starfive_jh7100"]
