[package]
name = "soc"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"

[profile.release]
opt-level = 'z'  # Optimize for size.

[dependencies]
cpu = { path = "../../../cpu/lowrisc/ibex"}
model = { path = "../../../drivers/model"}
clock = { path = "../../../drivers/clock" }
register = "0.3.2"
