[package]
name = "soc"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[profile.release]
opt-level = 'z'  # Optimize for size.

[dependencies]
cpu = { path = "../../../cpu/lowrisc/ibex"}
