image: rustlang/rust:nightly

before_script:
- rustup component add rustfmt

lint:
  script:
    - cargo fmt --all -- --check

# TODO: no nightly clippy
# clippy:
# script:
# - cargo clippy -- -D warnings

# TODO: cargo-make
# - cargo build
# TODO: we have no test yet...
# - cargo test
