[tasks.update-tools]
dependencies = [
    "update-layoutflash",
    "update-bin2vmem",
]

[tasks.update-layoutflash]
command = "cargo"
args = [ "install", "-f", "--path", "tools/layoutflash" ]

[tasks.update-bin2vmem]
command = "cargo"
args = [ "install", "-f", "--path", "tools/bin2vmem" ]

[tasks.setup]
dependencies = [
    "install-dependencies",
    "update-tools"
]

[tasks.install-dependencies]
dependencies = [
    "install-binutils",
    "install-llvm-tools",
]

[tasks.install-binutils]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [ "objcopy", "--help" ] }

[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools-preview" }
