[package]
name = "df"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
pci = { path = "../pci" }
vcell = "0.1.2"
heapless = "0.6.1"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
