[package]
name = "oreboot-arch"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
consts = { path = "../lib/consts" }
vcell = "0.1.3"

[features]
riscv64 = []
x86_64 = []
