[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/armv7r-none-eabi/debug"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/armv7r-none-eabi/release"

[tasks.default]
dependencies = ["bootblob"]
script = [
	"dtc fixed-dtfs.dts -O dtb -o ${TARGET_DIR}/fixed-dtfs.dtb",
	"echo layoutflash ${TARGET_DIR}/fixed-dtfs.dtb ${TARGET_DIR}/oreboot.bin",
]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/npcm7xx", "${TARGET_DIR}/bootblob.bin"]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/npcm7xx"]

[tasks.flash]
dependencies = ["default"]
script = [
       "echo not yet",
       "exit 1",
       "sudo $(which flashrom) -V -w ${TARGET_DIR}/oreboot.bin -p dediprog",
]
