OREBOOT=$(abspath $(CURDIR)/../../../../)
TARGET = armv7r-none-eabi
include ../../../../Makefile.inc
include ../../../../Makefile.mainboard.inc
cibuild: $(IMAGE)
ciclippy: skipclippy
citest: skiptest
