OREBOOT=$(abspath $(CURDIR)/../../../../)
TARGET     = x86_64-unknown-none
include ../../../../Makefile.inc
include ../../../../Makefile.mainboard.inc
cibuild:
	echo Skipping $(BOARD)
ciclippy: skipclippy
citest: skiptest
