[package]
name = "mp"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"

[dependencies]
smn = { path = "../smn"}

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
