
[package]
name = "arch"
version = "0.1.0"
authors = ["Ronald G. Minnich <rminnich@gmail.com>"]
edition = "2018"

[dependencies]
drivers = { path = "../../../drivers" }

[profile.release]
opt-level = 'z'  # Optimize for size.
