[package]
name = "oreboot-k230-main"
version = "0.1.0"
authors = ["oreboot authors"]
edition = "2021"

[dependencies]
embedded-hal = "=1.0.0"
embedded-hal-nb = "=1.0.0"
nb = "1"
spin = "0.9"

log = { path = "../../../../lib/log" }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
oreboot_compression = { path = "../../../../lib/compression" }

riscv = { version = "=0.12.1", features = ["critical-section-single-hart"] }
rustsbi = { version = "=0.4.0", features = ["machine"] }
sbi-spec = "0.0.4"

[features]
default = []
