[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C",
  "link-arg=-Tlink-nezha-main.ld",
  "-Z",
  "emit-stack-sizes",
  "-C",
  "target-feature=+zicsr,+zifencei",
]
