[package]
name = "oreboot-cpu"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
oreboot-arch = { path = "../arch", optional = true }
raw-cpuid = { version = "9.0.0", optional = true }

[features]
intel = []
