[package]
name = "starfive-visionfive2-main"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-nb = "1.0.0"
jh71xx-hal = { version = "0.1", features = ["rt"] }
jh71xx-pac = "0.3.2"
nb = "1"
riscv = "=0.10.1"
rustsbi = "0.3.2"
sbi-spec = "0.0.4"
spin = "0.9"

layoutflash = { path = "../../../../lib/layoutflash" }
log = { path = "../../../../lib/log" }
soc = { path = "../../../../soc", package = "oreboot-soc", features = ["starfive_jh7110"] }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
oreboot_compression = { path = "../../../../lib/compression" }

starfive-visionfive2-lib = { path = "../lib" }
