[package]
name = "starfive-visionfive2-main"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
embedded-hal-nb = "1.0.0-alpha.1"
nb = "1"
riscv = "0.10.1"
rustsbi = "0.3.2"
sbi-spec = "0.0.4"
spin = "0.9"

starfive-visionfive2-lib = { path = "../lib" }

log = { path = "../../../../lib/log" }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
oreboot_compression = { path = "../../../../lib/compression" }

# TODO
# [dependencies.oreboot-soc]
# path = "../../../../soc"
# features = ["starfive_jh7100"]
