[package]
name = "trembyle"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
console = { path = "../../../console" }
consts = { path="../../../lib/consts"}
print = { path = "../../../lib/print" }
payloads = { path = "../../../../payloads"}
util = { path = "../../../lib/util" }

heapless = "0.6.1"
raw-cpuid = "9.0.0"
tock-registers = "0.7.0"
static-ref = "0.1.1"
postcard = "0.7.3"
vcell = "0.1.3"
x86_64 = "0.14.8"

[dependencies.oreboot-arch]
path = "../../../arch"
features = ["x86_64"]

[dependencies.oreboot-cpu]
path = "../../../cpu"
features = ["amd"]

[dependencies.oreboot-soc]
path = "../../../soc"
# Remove amd_exclude_bootblock after bootblock.S hacking
features = ["amd_picasso", "amd_exclude_bootblock"]

[dependencies.oreboot-drivers]
path = "../../../drivers"
features = ["uart_i8250", "uart_debug_port", "uart_amdmmio"]
