[package]
name = "trembyle"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
console = { path = "../../../console" }
consts = { path="../../../lib/consts"}
cpu = { path = "../../../cpu/amd" }
print = { path = "../../../lib/print" }
payloads = { path = "../../../../payloads"}
soc = { path = "../../../soc/amd/picasso" }
util = { path = "../../../lib/util" }

heapless = "0.4.x"
raw-cpuid = "9.0.0"
tock-registers = "0.7.0"
static-ref = "0.1.1"
postcard = "0.4.3"
vcell = "0.1.2"
x86_64 = "0.14.8"

[dependencies.oreboot-arch]
path = "../../../arch"
features = ["x86_64"]

[dependencies.oreboot-drivers]
path = "../../../drivers"
features = ["uart_i8250", "uart_debug_port", "uart_amdmmio"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
