[package]
name = "smn"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
vcell = "0.1.2"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
