[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/debug/"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/release/"

[tasks.default]
dependencies = [ "build" ]
script = [
	"riscv64-linux-gnu-objcopy -O binary ${TARGET_DIR}/hifive ${TARGET_DIR}/oreboot.bin",
	"riscv64-linux-gnu-objdump -d ${TARGET_DIR}/hifive > oreboot.asm"
]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "512m", "-machine", "sifive_u", "-nographic", "-bios", "${TARGET_DIR}hifive", ]

[tasks.trace]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "512m", "-machine", "sifive_u", "-nographic", "-bios", "${TARGET_DIR}hifive", "-d", "guest_errors,in_asm"]

[tasks.gdb]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "512m", "-machine", "sifive_u", "-nographic", "-bios", "${TARGET_DIR}hifive", "-d", "guest_errors", "-s", "-S"]
