[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/debug"
DTS_SED_INPLACE = "s#/release/#/debug/#"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/release"
DTS_SED_INPLACE = "s#/debug/#/release/#"

[tasks.default]
dependencies = ["bootblob"]
script = [
	"sed -i \"${DTS_SED_INPLACE}\" fixed-dtfs.dts",
	"dtc fixed-dtfs.dts -O dtb -o ${TARGET_DIR}/fixed-dtfs.dtb",
	"layoutflash ${TARGET_DIR}/fixed-dtfs.dtb ${TARGET_DIR}/oreboot.bin",
]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "-R", ".bss", "${TARGET_DIR}/hifive", "${TARGET_DIR}/bootblob.bin"]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "1g", "-machine", "sifive_u,start-in-flash=true", "-nographic", "-device", "loader,addr=0x20000000,file=${TARGET_DIR}/oreboot.bin", "-bios", "none", "-smp", "4"]

[tasks.trace]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "1g", "-machine", "sifive_u,start-in-flash=true", "-nographic", "-device", "loader,addr=0x20000000,file=${TARGET_DIR}/oreboot.bin", "-bios", "none", "-d", "guest_errors,in_asm,int", "-smp", "4"]

[tasks.gdb]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "1g", "-machine", "sifive_u,start-in-flash=true", "-nographic", "-device", "loader,addr=0x20000000,file=${TARGET_DIR}/oreboot.bin", "-bios", "none", "-d", "guest_errors", "-s", "-S", "-smp", "4"]

[tasks.flash-openocd]
dependencies = ["default"]
script = ["$(which openocd) -f openocd.cfg -c \"flash write_image erase unlock ${TARGET_DIR}/oreboot.bin 0x20000000; shutdown\"",]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/hifive"]

[tasks.flash]
dependencies = ["default"]
script = [
       "sudo $(which flashrom) -V -w ${TARGET_DIR}/oreboot.bin -p dediprog",
]
