[package]
name = "zimage"
version = "0.1.0"
authors = ["Ryan O'Leary <ryan@ryanoleary.ca>"]
edition = "2018"

[lib]
name = "zimage"
path = "zimage.rs"

[dependencies]
payload = { path = "../../payload"}

[profile.release]
opt-level = 'z'  # Optimize for size.
