[package]
name = "payloads"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"

[dependencies]
model = { path = "../src/drivers/model"}

[profile.release]
opt-level = 'z'  # Optimize for size.
