[package]
name = "crb"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"
build = "build.rs"

[dependencies]
arch = { path = "../../../arch/riscv/rv32"}
console = { path = "../../../console" }
print = { path = "../../../lib/print" }
model = { path = "../../../drivers/model" }
payloads = { path = "../../../../payloads"}
soc = { path = "../../../soc/opentitan/earlgrey" }
wrappers = { path = "../../../drivers/wrappers"}

register = "0.3.2"
static-ref = "0.1.1"

[dependencies.uart]
path = "../../../drivers/uart"
features = ["sifive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
