[package]
name = "crb"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
console = { path = "../../../console" }
print = { path = "../../../lib/print" }
payloads = { path = "../../../../payloads"}

tock-registers = "0.7.0"
static-ref = "0.1.1"

[dependencies.oreboot-soc]
path = "../../../soc"
features = ["opentitan_earlgrey"]

[dependencies.oreboot-drivers]
path = "../../../drivers"
features = ["uart_opentitan"]
