[package]
name = "crb"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
console = { path = "../../../console" }
print = { path = "../../../lib/print" }
model = { path = "../../../drivers/model" }
payloads = { path = "../../../../payloads"}
soc = { path = "../../../soc/opentitan/earlgrey" }
wrappers = { path = "../../../drivers/wrappers"}

tock-registers = "0.7.0"
static-ref = "0.1.1"

[dependencies.uart]
path = "../../../drivers/uart"
features = ["opentitan"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
