[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/riscv32imc-unknown-none-elf/debug"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/riscv32imc-unknown-none-elf/release"

# TODO: determine the actual correct size of flash.bin and oreboot.bin
[tasks.default]
dependencies = ["bootblob"]
script = [
	"dd if=${TARGET_DIR}/bootblob.bin of=${TARGET_DIR}/rom.bin ibs=2048 count=1",
	"dd if=${TARGET_DIR}/bootblob.bin of=${TARGET_DIR}/flash.bin ibs=32768 skip=16383",
	"dd if=${TARGET_DIR}/bootblob.bin of=${TARGET_DIR}/flash.bin ibs=32768 count=1 skip=16383",
	"dtc fixed-dtfs.dts -O dtb -o ${TARGET_DIR}/fixed-dtfs.dtb",
	"layoutflash ${TARGET_DIR}/fixed-dtfs.dtb ${TARGET_DIR}/oreboot.bin",
	"bin2vmem -o 0 <${TARGET_DIR}/rom.bin >${TARGET_DIR}/rom.vmem",
	"bin2vmem -o 0 <${TARGET_DIR}/oreboot.bin >${TARGET_DIR}/oreboot.vmem",
	"bin2vmem -o 0 <${TARGET_DIR}/flash.bin >${TARGET_DIR}/oreboot.vmem",
]

[tasks.bootblob]
dependencies = [ "build" ]
script = [
	"cargo objcopy -- -O binary -R .bss ${TARGET_DIR}/crb ${TARGET_DIR}/bootblob.bin"
]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.run]
dependencies = ["default"]
command = "Vtop_earlgrey_verilator"
args = ["-t", "--rominit=${TARGET_DIR}/rom.vmem",
	"--flashinit=${TARGET_DIR}/oreboot.vmem" ]

[tasks.objdump]
dependencies = [ "build" ]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/crb"]

[tasks.flash]
dependencies = ["default"]
script = [
       "sudo $(which flashrom) -V -w ${TARGET_DIR}/oreboot.bin -p dediprog",
]
