// These are the header files for the QEMU FSP.
// Note they are generated by the fspsdk build.
#include <FspmUpd.h>
#include <FspsUpd.h>
#include <FsptUpd.h>
#include <FspUpd.h>

// Data types to parse FSP structure.
#include <Guid/FspHeaderFile.h>
#include <Pi/PiFirmwareFile.h>
#include <Pi/PiFirmwareVolume.h>

// BOOT_MODE
#include <Pi/PiBootMode.h>
