[package]
name = "beaglev"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
consts = { path = "../../../lib/consts" }
console = { path = "../../../console" }
device_tree = { path = "../../../lib/device_tree" }
print = { path = "../../../lib/print" }
payloads = { path = "../../../../payloads"}

heapless = "0.6.1"
static-ref = "0.1.1"

[dependencies.oreboot-arch]
path = "../../../arch"
features = ["riscv64"]

[dependencies.oreboot-soc]
path = "../../../soc"
features = ["starfive_jh7100"]

[dependencies.oreboot-drivers]
path = "../../../drivers"
features = ["spi_sifive", "uart_sifive", "uart_log", "heapless"]
