[package]
name = "beaglev"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"
build = "build.rs"

[dependencies]
consts = { path = "../../../lib/consts" }
console = { path = "../../../console" }
device_tree = { path = "../../../lib/device_tree" }
print = { path = "../../../lib/print" }
payloads = { path = "../../../../payloads"}
soc = { path = "../../../soc/starfive/jh7100" }

heapless = "0.4.x"
static-ref = "0.1.1"

[dependencies.oreboot-arch]
path = "../../../arch"
features = ["riscv64"]

[dependencies.oreboot-drivers]
path = "../../../drivers"
features = ["spi_sifive", "uart_sifive", "uart_log", "heapless"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
