#!/bin/bash
set -x
set -e

# TODO: put this into build.rs
function handle_file {
	inFile=$1
	echo inFile: $inFile
	outFile=$inFile.out

	inSize=`stat -c "%s" $inFile`
	inSize32HexBe=`printf "%08x\n" $inSize`
	inSize32HexLe=${inSize32HexBe:6:2}${inSize32HexBe:4:2}${inSize32HexBe:2:2}${inSize32HexBe:0:2}
	echo "inSize: $inSize (0x$inSize32HexBe, LE:0x$inSize32HexLe)"

	echo $inSize32HexLe | xxd -r -ps > $outFile
	cat $inFile >> $outFile
	echo outFile: $outFile

	outSize=`stat -c "%s" $outFile`
	outSize32HexBe=`printf "%08x\n" $outSize`
	echo "outSize: $outSize (0x$outSize32HexBe)"
}

#if [ "$1" = "" -o "$1" = "--help" ]; then
#	echo "Add file size(32bits, Little Endian) before the content."
#	echo "Usage: ./fsz.sh <file>"
#	exit 1
#fi

echo empty sudo so we do not need another password prompt
sudo date

make

echo "power on, hold down reset, once jh7100 starts"

cp target/riscv64imac-unknown-none-elf/release/bootblob.bin .

handle_file bootblob.bin
ls -l bootblob.bin*

sudo strace -o shit -f -s 1024 -v \
     /home/rminnich/bin/jh7100-recover \
     -D /dev/ttyUSB0 \
     -r /home/rminnich/riscv/vic_second_boot.bin \
     -b  bootblob.bin.out \

     exit 0
     -d /home/rminnich/riscv/ddrinit-2133-210302.bin.out
