[package]
name = "wrappers"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
model = { path = "../model"}
consts = { path = "../../lib/consts"}

[profile.release]
opt-level = 'z'  # Optimize for size.
