[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/armv7r-none-eabi/debug"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/armv7r-none-eabi/release"

[tasks.default]
dependencies = ["bootblob"]
script = [
	"sed s^\\$TARGET_DIR^${TARGET_DIR}^g fixed-dtfs.dts | dtc -O dtb -o ${TARGET_DIR}/fixed-dtfs.dtb",
	"layoutflash ${TARGET_DIR}/fixed-dtfs.dtb ${TARGET_DIR}/oreboot.bin",
	"echo \">>> Done, output is at ${TARGET_DIR}/oreboot.bin <<<\"",
]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/ast25x0", "${TARGET_DIR}/bootblob.bin"]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/ast25x0"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-arm"
args = [
	"-m", "512", "-M", "ast2500-evb", "-display", "none",
	"-drive", "file=${TARGET_DIR}/oreboot.bin,format=raw,if=mtd",
	"-serial", "mon:stdio", "-d", "in_asm,guest_errors" ]
