[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/arm-none-eabihf/debug/"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/arm-none-eabihf/release/"

[tasks.default]
dependencies = [ "build" ]
script = [
	"arm-none-eabi-objcopy -O binary ${TARGET_DIR}/ast25x0 ${TARGET_DIR}/oreboot.bin",
	"truncate -s 33554432 ${TARGET_DIR}/oreboot.bin"
]

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-arm"
args = ["-m", "512m", "-machine", "ast2500-evb", "-nographic", "-drive", "file=${TARGET_DIR}oreboot.bin,format=raw,if=mtd", "-d", "guest_errors"]
