[package]
name = "boot"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
console = { path = "../../../../console" }
cpu = { path = "../../../../cpu/amd" }
heapless = "0.4.x"
print = { path = "../../../../lib/print" }
payloads = { path = "../../../../../payloads"}
raw-cpuid = "9.0.0"
smn = { path = "../../../../soc/amd/common/smn" }
util = { path = "../../../../lib/util" }

[dependencies.oreboot-arch]
path = "../../../../arch"
features = ["x86_64"]

[dependencies.oreboot-drivers]
path = "../../../../drivers"
features = ["uart_i8250", "uart_debug_port", "uart_amdmmio"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
