[package]
name = "payload"
version = "0.1.0"
authors = ["Ryan O'Leary <ryan@ryanoleary.ca>"]
edition = "2018"

[lib]
name = "payload"
path = "payload.rs"

[profile.release]
opt-level = 'z'  # Optimize for size.
