[package]
name = "model"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"

[dependencies]
consts = { path = "../../lib/consts"}

[profile.release]
opt-level = 'z'  # Optimize for size.
