# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "sipeed-m1s-dock-e907"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
embedded-hal = "=1.0.0-alpha.8"
nb = "1"
riscv = "0.9.0"
spin = "0.9"
