# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "sipeed-m1s-dock-e907"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
bl808-pac = { git = "https://github.com/bouffalolab/bl808-pac", commit = "3bbd010", features = ["rt", "critical-section"] }
critical-section = "1.0"
embedded-hal = "=1.0.0-alpha.8"
log = { path = "../../../../lib/log" }
nb = "1"
riscv = { version = "0.10.1", features = ["critical-section-single-hart"] }
riscv-rt = "0.11.0"
spin = "0.9"
