[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/debug"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/riscv64imac-unknown-none-elf/release"

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.default]
dependencies = ["resizeblob"]

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/oreboot", "${TARGET_DIR}/bootblob.bin"]

[tasks.resizeblob]
dependencies = [ "bootblob" ]
command = "qemu-img"
args = ["resize", "${TARGET_DIR}/bootblob.bin", "16777216"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-riscv64"
args = ["-m", "1g", "-machine", "virt", "-nographic", "-bios", "${TARGET_DIR}/oreboot"]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/oreboot"]
