[package]
name = "arch"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2021"

[dependencies]
model = { path = "../../../drivers/model" }
consts = { path="../../../lib/consts"}

[profile.release]
opt-level = 'z'  # Optimize for size.
