[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acpi = { path = "../../../../lib/acpi" }
cpu = { path = "../../../../cpu", package = "oreboot-cpu" }
consts = { path = "../../../../lib/consts" }
bootmode = { path = "../../../../lib/bootmode" }
buddy_system_allocator = "0.8"
ec = { path = "../../../../ec", features = ["intel"] }
fsp = { path = "../../../../vendorcode/fsp/apollolake", package = "fsp-apl-sys" }
payload = { path = "../../../../lib/payload" }
soc = { path = "../../../../soc", package = "oreboot-soc", features = ["intel", "geminilake"] }
variants = { path = "../variants" }

[features]
bobba = ["variants/bobba"]
