[package]
name = "milkv-meles-bt0"
version = "0.1.0"
authors = [
  "Daniel Maslowski <info@orangecms.org>",
]
edition = "2021"

[dependencies]
bitfield = "0.13.2"
embedded-hal = "1.0.0"
embedded-hal-nb = "1.0.0"
nb = "1"
riscv = "0.10.1"
spin = "0.9"

layoutflash = { path = "../../../../lib/layoutflash" }
log = { path = "../../../../lib/log" }
oreboot_util = { package = "util", path = "../../../../lib/util" }
