name: qemu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildX86QEMU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install Dependencies'
      run: sudo apt-get update && make ciprepare
    - name: 'Build QEMU q35 board for x86'
      run: |
        cd src/mainboard/emulation/qemu-q35
        make mainboard
    - name: 'Check QEMU q35 stack size'
      run: |
        cd src/mainboard/emulation/qemu-q35
        STACK_SIZES=$(make stack-sizes | tee /dev/stdout)
        if ! echo "$STACK_SIZES" | grep '0x[0-9a-f]\+\s\+[0-9]\+\s\+_start' > /dev/null; then
          echo "Error: Didn't see stack size of _start. make stack-sizes might be broken."
          exit 1
        fi

  BuildFSPQEMU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install Dependencies'
      run: sudo apt-get update && make ciprepare
    - name: 'Build FSP QEMU firmware'
      run: |
        cd src/mainboard/emulation/qemu-fsp
        make mainboard
    - name: 'Check FSP QEMU stack size'
      run: |
        cd src/mainboard/emulation/qemu-fsp
        STACK_SIZES=$(make stack-sizes | tee /dev/stdout)
        if ! echo "$STACK_SIZES" | grep '0x[0-9a-f]\+\s\+[0-9]\+\s\+_start' > /dev/null; then
          echo "Error: Didn't see stack size of _start. make stack-sizes might be broken."
          exit 1
        fi
    - name: 'Run FSP QEMU firmware in QEMU'
      run: |
        (
          cd src/mainboard/emulation/qemu-fsp
          timeout 120s make run | tee serial
          grep Running.payload serial
        )

  TestRISCVVirtBoardQEMU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install Dependencies'
      run: sudo apt-get update && make ciprepare
    - name: 'Build oreboot image'
      run: |
        (
          cd src/mainboard/emulation/qemu-riscv
          make mainboard
          STACK_SIZES=$(make stack-sizes | tee /dev/stdout)
          if ! echo "$STACK_SIZES" | grep '0x[0-9a-f]\+\s\+[0-9]\+\s\+_start' > /dev/null; then
            echo "Error: Didn't see stack size of _start. make stack-sizes might be broken."
            exit 1
          fi
        )
    - name: 'Build QEMU'
      run: |
        sudo apt-get install qemu-system-misc
    - name: 'Run test'
      run: |
        (
          cd src/mainboard/emulation/qemu-riscv
          timeout 30s make run | tee serial
          grep "Running payload" serial
        )
